### ISSUE TITLE
Unable to create image for spring boot

### ISSUE THREAD

**Issue by sendev1** [mike-neck/graalvm-native-image-plugin#59]
Downloaded spring boot app from spring initializr and added plugin dependencies and added gradle task to build native image but the task is failing. Please see below image
![image](https://user-images.githubusercontent.com/68568448/88072984-4cc96f00-cb3b-11ea-8f9d-fe1a0047ce19.png)

**Comment by mike-neck** [comment]
This plugin depends on `jar` task and uses the jar file created by the task. But `org.springframework.boot` plugin make the `jar` task disabled so that there are no jar file in classpath which contains the main class.

This plugin is not intended to be applied to Spring application. If you want to create a native binary of a Spring application, it is recommended to use [spring-graalvm-native](https://github.com/spring-projects-experimental/spring-graalvm-native) project.

**Comment by mike-neck** [comment]
Please use spring-graalvm-native for a spring-boot application.
